name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    - name: Cove Coverage
      run: mvn cobertura:cobertura --file def/pom.xml

    - name: Submit to codecov.io 
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }} #required
        file: ./def/target/site/cobertura/coverage.xml #optional
        flags: unittests #optional
        name: codecov-umbrella #optional
        #yml: ./codecov.yml #optional
        fail_ci_if_error: true #optional (default = false)
    
    - name: Build with Maven
      run: mvn -B package -f def/pom.xml

    - name: Publish to GitHub Repositories
      run: mvn -B deploy -f def/pom.xml -Dregistry=https://maven.pkg.github.com/kkazakevich -Dtoken=GH_TOKEN
